### ISSUE TITLE
Exceptions when running DSpot over JUnit5 version of DHell

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [STAMP-project/dspot#791]
#### Characteristics
- **Issue Type**: bug
- **Reproducibility**: always
- **Severity**: major
- **Tool/Service/Component**: DSpot, lastest from sources
- **Execution Environment**: Linux
- **Reporter**: Jesús Gorroñogoitia(jesus.gorronogoitia@atos.net)

#### Description
For testing DSpot parallel execution support for JUnit5, I've created JUnit5 version of DHell tests in 
[DHell dspot_optimization branch ](https://github.com/STAMP-project/dhell/tree/dspot_optimization)

See tests with names JUnit5_*Test.java
When running DSpot (master branch) on eu.stamp_project.examples.dhell.JUnit5_HelloAppTest, in normal (no parallel) execution, I get multiple exceptions, such as:
```
java.lang.RuntimeException: java.lang.RuntimeException: java.io.OptionalDataException
	at eu.stamp_project.compare.ObjectLog.load(ObjectLog.java:250)
	at eu.stamp_project.compare.ObjectLog.getObservations(ObjectLog.java:212)
	at eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator.addAssertions(MethodsAssertGenerator.java:133)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.innerAssertionAmplification(AssertGenerator.java:136)
	at eu.stamp_project.dspot.assertgenerator.AssertGenerator.assertionAmplification(AssertGenerator.java:76)
	at eu.stamp_project.dspot.Amplification.assertionsAmplification(Amplification.java:214)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:108)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:273)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$5(DSpot.java:254)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:255)
	at eu.stamp_project.Main.run(Main.java:65)
	at eu.stamp_project.Main.main(Main.java:44)
Caused by: java.lang.RuntimeException: java.io.OptionalDataException
	at eu.stamp_project.compare.ObjectLog.load(ObjectLog.java:247)
	... 18 more
Caused by: java.io.OptionalDataException
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1593)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at java.util.HashMap.readObject(HashMap.java:1410)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1170)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:2178)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:2069)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1573)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:431)
	at eu.stamp_project.compare.ObjectLog.load(ObjectLog.java:245)
	... 18 more
```
and

```
Exception in thread "main" java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at eu.stamp_project.utils.AmplificationHelper.lambda$null$7(AmplificationHelper.java:213)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at eu.stamp_project.utils.AmplificationHelper.lambda$getPassingTests$8(AmplificationHelper.java:213)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.utils.AmplificationHelper.getPassingTests(AmplificationHelper.java:214)
	at eu.stamp_project.utils.compilation.TestCompiler.compileRunAndDiscardUncompilableAndFailingTestMethods(TestCompiler.java:61)
	at eu.stamp_project.dspot.Amplification.assertionsAmplification(Amplification.java:225)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:186)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:131)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:273)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$5(DSpot.java:254)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:255)
	at eu.stamp_project.Main.run(Main.java:65)
	at eu.stamp_project.Main.main(Main.java:44)
```
It seems the object serialization of test execution results is incorrect for JUnit5 tests. When Results.ser is deserialized some NPE are triggered.

I noticed this when I was running DSpot for JUnit5 parallel execution, so I decided to try it out first with the master (original) DSpot version. 

DHell JUnit5 tests are working fine when executed both with Java CMD and Maven. They are also working fine when they are executed in parallel mode outside DSpot.

#### Steps to reproduce
Clone dspot_optimization branch of DHell project. Edit run_dspot_2.sh script and fix the relative path (from this script) to the DSpot library:
`dspotJar=`ls ../dspot/dspot/target/*dependencies.jar`
`
Run ./run_dspot_2.sh

#### [Help on issue template](https://github.com/STAMP-project/dspot/blob/master/.github/ISSUE_DOC.md) 
Preview to follow the link or open file .github/ISSUE_DOC.md

**Comment by danglotb** [comment]
Looking at this

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
Could you get some time to have a look on this. In last days I've been busy working on other projects, but now I can come back to STAMP and on this issue in particular.
The point is that I will need help (or clues) to investigate what is going on with the standard DSpot (without parallelization) with JUnit5 tests.
Do you have any JUnit5 test for which DSpot is working fine?
From logs, I understand that that there is a problem to deserialize the results of the JUnit5 tests execution, so there must be a problem when this test execution results are collected and serialized. Is DSpot using the same approach for JUnit4/5 to collect tests results and store them or a different approach? Meantime I wait for you to provide some hints I will spend some time debugging and investigating.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I've found the reason of the triggered NPE. This is trigger by Spoon when AssertionRemover is trying to remove this assertion:
`org.junit.jupiter.api.Assertions.assertTrue(((myApp.getMyAppSystemInformation(true)) != null), () -> "App should return some info")`

For such CtInvocation, the first argument is of type CtLambda:
`() -> "App should return some info"`
whose body is null, and this is causing the NPE in AssertionRemover:87 because the Spoon factory method createStatementList() receives a null object.

I am not sure how to fix this in AsssertionRemover (I don't have the knowledge this class is supposed to do), so I will try to modify my JUnit5 test so it is not causing this problem, but the bug will remain, unless you know how to fix it.
If you know how this should fix, please, let me know.

I will let you know if I can overcome this NPE issue and if solved, the remaining exceptions are gone or stay.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
By fixing the JUnit5 test to avoid using lambdas with empty arguments block I will progress but still not working because a NPE in EntryPoint.runTests: 209 because the deserialized TestResult load contains one null entry in it runningTest list.
I will investigate where and how this object is serialized and the reason it contains a null test

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

Sorry, I was very busy the last weeks.

I opened #811 that should fix the issue with lambdas.

I'll investigate the issue of serialization now.

Thank you.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
Thanks, as commented, the point is that the TestResults returns sometimes a null entry in the list of executed tests, I guess when it recovers its name. 
It is hard for me to debug it (I am on it) because the TestRunner is launched in another forked JVM.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I confirm that JUnit5Runner.main in line 39 is sometimes saving a list with a null entry:
`TestResultImpl{runningTests=[null, testHelloAppDefault], failingTests=[], assumptionFailingTests=[], ignoredTests=[]}`

I need to find the reason of this NP

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
The behavior of JUnit5TestResult.executionStarted method is weird in the sense that if I add a log entry to see what is being added to the runningTests array the NPE never occurs, but if I check the test method name value that is going to be added, without any additional log, I still get an extra null entry (first one) in the runningTests list, causing the NPE.
So with this method code, I am still facing the NPE:
```
 public void executionStarted(TestIdentifier testIdentifier) {
        if (testIdentifier.isTest()) {
            String testname = this.toString.apply(testIdentifier);
            if (testname!=null) {
                this.getRunningTests().add(testname);
            }
        }
    }
```
but this this one, logging the entry, the NPE never happens:
```
 public void executionStarted(TestIdentifier testIdentifier) {
        if (testIdentifier.isTest()) {
            String testname = this.toString.apply(testIdentifier);
            if (testname!=null) {
                System.out.println ("****** JUnit5TestResult.executionStarted. Added test: " + testname);
                this.getRunningTests().add(testname);
            }
        }
    }
```

Once I get rid of the NPE, the OptionalDataException persists any time DSpot is trying to load the TestResults.ser in ObjectLog.log method. This exception eof is true, so it is caused because it tries to read beyond the available file.
Any idea for both issues?
Regards
Yosu

**Comment by jesus-gorronogoitia** [comment]
In logs, the TestResult.ser file is store and load one after another, I assume with the same ObjectLog class:

```
File saved to the following path: /home/yosu/Projects/STAMP/Git/dhell/target/dspot/TestResult.ser
Loading /home/yosu/Projects/STAMP/Git/dhell/target/dspot/TestResult.ser
```
Any idea to propose?
Thanks
Yosu

**Comment by danglotb** [comment]
Hi Yosu, 

I'm sorry for the delay, but I wanted to finish what I've started.

I'm making now the resolution of this issue my highest priority.

I'm gonna first try to well understand what is happening, it should not be difficult since you investigated very well the problem.

Coming back very soon to keep you update.

Again, I'm very sorry for this delay.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb don't worry, I will try to get progress by myself. Just to let you know that without being able to run DSpot on JUnit5 tests, I won't be able to get progress on performance optimization based on parallel execution. Nonetheless, I will dedicate time to this issue to get progress.
Take your time in the stuff you have on your hands, don't worry about this. Just let me know when you are available.

**Comment by jesus-gorronogoitia** [comment]
Sorry, the information I gave you above is wrong. The problem happens when reading the Observations.ser, not the TestResults.ser

**Comment by jesus-gorronogoitia** [comment]
I confirm (by debugging) that Observations.ser are created by:
```
eu.stamp_project.compare.ObjectLog.save(ObjectLog.java:223)
eu.stamp_project.examples.dhell.JUnit5_HelloAppTest.runOnceAtTheEnd(JUnit5_HelloAppTest.java:13)
```
and load by:
```
eu.stamp_project.compare.ObjectLog.getObservations(ObjectLog.java:213)
eu.stamp_project.dspot.assertgenerator.MethodsAssertGenerator.addAssertions(MethodsAssertGenerator.java:133)
```
in this order.
But, as commented above, when reading the object (Observations.ser) an EOF is found before completing the reading. 
As I have no idea how to solve this, I will search in Internet above the topic

**Comment by danglotb** [comment]
I think something wrong happened during the observations. 

A wrong value might be stored in the map. This value can be saved, but not loaded.


For the `null` value in the test result, I do not know (yet) why it happens, nor when. Indeed, this `null` is sometimes presents, sometimes not.

To be investigated.

**Comment by jesus-gorronogoitia** [comment]
Amazing, just adding a log in Observation.add method remove any occurrence of above exception.
Same behavior as commented before for TestRunner and NPE.
I will clean up everything keeping only these minimum changes and I will try it out again.
I'll keep you informed

**Comment by jesus-gorronogoitia** [comment]
DSpot behavior is getting crazy (facepalm). Above reported solution works well on debug in Eclipse, but not when run in CLI (this case triggers the reported exceptions). So, I need to investigate further.

**Comment by danglotb** [comment]
Hello @jesus-gorronogoitia 

which version of `test-runner` are you using?

**Comment by jesus-gorronogoitia** [comment]
Hi,
The one I forked:
https://github.com/jesus-gorronogoitia/testrunner/tree/fixIssue791

But with this one, the NPE has gone,
The problem persist on the loading of the serialization of Observation.ser with launches a java.io.OptionalDataException.

I've added logs to ObjectLog to see what sort of Observations are stored, but I see nothing strange. For instance these logs are output when saving an Observations.ser that in turn, when read, triggers the exception:
```
Storing observations:
	Observation testHelloAppRun1__1 values:
Observation value (key=myApp, value=null)
	Observation testHelloAppRun1__3 values:
Observation value (key=fileContent, value=null)
	Observation testHelloAppDefault__1 values:
Observation value (key=myTracesName, value=myHelloApp.traces)
File saved to the following path: /home/yosu/Projects/STAMP/Git/dhell/target/dspot/observations.ser

```
But I don't see nothing strange.
However, the Observations.ser cannot be loaded.

I give up by today, I will continue investigating tomorrow.

**Comment by danglotb** [comment]
I added `synchronized` keyword to methods that have access to the `observations` of `ObjectLog` and updated to `test-runner-2.1.1-SNAPSHOT`.

It seems that the problem vanished... It was probably due to concurrent access or something, idk.

**Comment by jesus-gorronogoitia** [comment]
Excellent! thanks, I will try it out tomorrow.

**Comment by jesus-gorronogoitia** [comment]
Did you commit your changes to DSpot master? I get no updates

**Comment by danglotb** [comment]
No, I did not yet.

I openned STAMP-project/testrunner#72 and #813.

Do you think that we should also merge your workaround in `test-runner`?

**Comment by jesus-gorronogoitia** [comment]
How can I get your changes? Should you merge your pull requests? Or can I merge them locally, test them and report you?

In case the latter, please, send me the git recipes.

On 5/6/19 18:55, Benjamin DANGLOT wrote:

No, I did not yet.

I openned STAMP-project/testrunner#72<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSTAMP-project%2Ftestrunner%2Fpull%2F72&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7Cd494825e15094a19432408d6e9d69869%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636953505228963519&sdata=cETpXN%2BRvyNxEoJKhwDEQvfUP7wSh%2FtOMh53ZFlj068%3D&reserved=0> and #813<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSTAMP-project%2Fdspot%2Fpull%2F813&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7Cd494825e15094a19432408d6e9d69869%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636953505228963519&sdata=VNnvtDFOLXKJkVvW3q6Qc9p6EswI2ST8dCcp%2B3zf9s0%3D&reserved=0>.

Do you think that we should also merge your workaround in test-runner?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FSTAMP-project%2Fdspot%2Fissues%2F791%3Femail_source%3Dnotifications%26email_token%3DAA35ES7ZAR4XA7CGHWDJIRTPY7VWVA5CNFSM4HMQSWJKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXALAUY%23issuecomment-499167315&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7Cd494825e15094a19432408d6e9d69869%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636953505228963519&sdata=NajDOTGO6qWZCgocnupua0reKY4gxUYJWwk0%2B2mFaKE%3D&reserved=0>, or mute the thread<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAA35ES5PQNNJIKWA3DITG4DPY7VWVANCNFSM4HMQSWJA&data=02%7C01%7Cjesus.gorronogoitia%40atos.net%7Cd494825e15094a19432408d6e9d69869%7C33440fc6b7c7412cbb730e70b0198d5a%7C0%7C0%7C636953505228973512&sdata=jvSDxqjqgRaFKBwG%2BuHHTKNJdvMbXnmMbAH%2B7dkZWzE%3D&reserved=0>.

This e-mail and the documents attached are confidential and intended solely for the addressee; it may also be privileged. If you receive this e-mail in error, please notify the sender immediately and destroy it.
As its integrity cannot be secured on the Internet, the Atos group liability cannot be triggered for the message content. Although the sender endeavors to maintain a computer virus-free network, the sender does not warrant that this transmission is virus-free and will not be liable for any damages resulting from any virus transmitted.

Este mensaje y los ficheros adjuntos pueden contener información confidencial destinada solamente a la(s) persona(s) mencionadas anteriormente y pueden estar protegidos por secreto profesional.
Si usted recibe este correo electrónico por error, gracias por informar inmediatamente al remitente y destruir el mensaje.
Al no estar asegurada la integridad de este mensaje sobre la red, Atos no se hace responsable por su contenido. Su contenido no constituye ningún compromiso para el grupo Atos, salvo ratificación escrita por ambas partes.
Aunque se esfuerza al máximo por mantener su red libre de virus, el emisor no puede garantizar nada al respecto y no será responsable de cualesquiera daños que puedan resultar de una transmisión de virus.

**Comment by danglotb** [comment]
Hi,

It would be great that you try the changes before the merge.

```
git remote add danglotb https://github.com/danglotb/dspot.git
git fetch danglotb fix-concurrent-modification-for-dhell-junit5
git checkout  fix-concurrent-modification-for-dhell-junit5
```

and you should have the changes. You can still check if you do with a `git log` and see if you have my commits.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb 
I've just tried your patch, but it does work (I launched the script run_dspot_2.sh)
I get this exception:

```
Loading /home/yosu/Projects/STAMP/Git/dhell/target/dspot/TestResult.ser
[WARN] 2019-06-06 10:22:03 ErrorReport - Something bad happened when DSpot tried to execute the tests before starting the amplification.
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at eu.stamp_project.utils.AmplificationHelper.lambda$null$7(AmplificationHelper.java:213)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:498)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:449)
	at eu.stamp_project.utils.AmplificationHelper.lambda$getPassingTests$8(AmplificationHelper.java:213)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.utils.AmplificationHelper.getPassingTests(AmplificationHelper.java:214)
	at eu.stamp_project.utils.compilation.TestCompiler.compileRunAndDiscardUncompilableAndFailingTestMethods(TestCompiler.java:61)
	at eu.stamp_project.dspot.Amplification.amplification(Amplification.java:92)
	at eu.stamp_project.dspot.DSpot._amplify(DSpot.java:274)
	at eu.stamp_project.dspot.DSpot.lambda$amplifyTestClassesTestMethods$5(DSpot.java:255)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.dspot.DSpot.amplifyTestClassesTestMethods(DSpot.java:256)
	at eu.stamp_project.Main.run(Main.java:65)
	at eu.stamp_project.Main.main(Main.java:44)

[INFO] 2019-06-06 10:22:03 DSpot - elapsedTime 1327
[WARN] 2019-06-06 10:22:03 DSpot - DSpot could not obtain any amplified test method.
[WARN] 2019-06-06 10:22:03 DSpot - You can customize the following options: --amplifiers, --test-criterion, --iteration, --budgetizer etc, and retry with a new configuration.
[INFO] 2019-06-06 10:22:03 Main - Amplification succeed.
[INFO] 2019-06-06 10:22:03 Main - Elapsed time 1542 ms
Exception in thread "main" java.lang.NullPointerException
	at eu.stamp_project.utils.report.output.selector.TestSelectorReportImpl.lambda$output$0(TestSelectorReportImpl.java:35)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.HashMap$KeySpliterator.forEachRemaining(HashMap.java:1556)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at eu.stamp_project.utils.report.output.selector.TestSelectorReportImpl.output(TestSelectorReportImpl.java:36)
	at eu.stamp_project.utils.report.GlobalReport.output(GlobalReport.java:35)
	at eu.stamp_project.Main.main(Main.java:47)

```

Note that I changed the Dhell JUnit5 test (I did not commit the changes) so the Dhell JUnit5 test does not anymore uses lambdas. These are the code lines I changed:
![image](https://user-images.githubusercontent.com/3658315/59018275-cf16a700-8845-11e9-9884-0069b91bd65a.png)

Essentially, I replace the lambda by an string.

I will debug it after the meeting to see what is going on.

**Comment by jesus-gorronogoitia** [comment]
Hi @danglotb forget previous message, this NPE is our old friend triggered when reading the list of passing tests I already reported here above. So, TestRunner needs to be synchronized, I think. I will take care after our monthly meeting.

**Comment by jesus-gorronogoitia** [comment]
Hi  @danglotb 
Solved! Very simple modification in TestRunner JUInit5TestResult.java
Just added synchronized keyword to method void executionStarted (TestIdentifier testIdentification)

Do you want me to create a PR with that change? Or can you patched directly in your master branch?

As a matter for fact, we should consider that synchronization problems when reading tests executions could be behind weird and random DSpot behavior

**Comment by jesus-gorronogoitia** [comment]
Please @danglotb accept your PR in DSpot

**Comment by danglotb** [comment]
> Do you want me to create a PR with that change? Or can you patched directly in your master branch?

I'll add the changes to my own PR

> As a matter for fact, we should consider that synchronization problems when reading tests executions could be behind weird and random DSpot behavior

Yes, it seems logic.

> Please @danglotb accept your PR in DSpot

Done
